// Constantes de módulos — sem código server-side para poder importar em Client Components

export const ALL_MODULES: readonly string[] = [
  "agenda",
  "alertas",
  "analytics",
  "atividades",
  "brindes",
  "campanhas",
  "configuracoes",
  "conversas",
  "corretores",
  "dashboard",
  "imoveis",
  "leads",
  "mensagens",
  "obras",
  "pipeline",
  "sistema",
  "treinamento",
] as const

export const MODULE_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  pipeline: "Pipeline",
  leads: "Leads",
  imoveis: "Imóveis",
  corretores: "Corretores",
  conversas: "Conversas",
  agenda: "Agenda",
  alertas: "Alertas",
  atividades: "Atividades",
  analytics: "Analytics",
  campanhas: "Campanhas",
  treinamento: "Treinamento",
  obras: "Obras",
  brindes: "Brindes",
  mensagens: "Mensagens",
  configuracoes: "Configurações",
  sistema: "Sistema",
}

export const MODULE_DESCRIPTIONS: Record<string, string> = {
  dashboard: "Visão geral e métricas",
  pipeline: "Kanban de oportunidades",
  leads: "Cadastro e qualificação",
  imoveis: "Catálogo de propriedades",
  corretores: "Equipe e performance",
  conversas: "Mensagens e atendimento",
  agenda: "Eventos e compromissos",
  alertas: "Notificações e follow-ups",
  atividades: "Histórico de ações",
  analytics: "Relatórios avançados",
  campanhas: "Marketing e automação",
  treinamento: "Conteúdos e cursos",
  obras: "Acompanhamento de obras",
  brindes: "Presentes e brindes",
  mensagens: "Comunicação interna",
  configuracoes: "Preferências da org",
  sistema: "Administração total",
}
